version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/downloadr cmd/main.go
