version: v1.0
name: build-1
stages:
- build
- package
jobs:
- job: build
  stage: build
  steps:
  - script:
    - echo "Building my application"
  - CDS_GoBuild:
      architecture: amd64
      artifactUpload: "true"
      binary: '{{.cds.application}}-linux-amd64'
      cgoDisabled: "true"
      detectRaceCondition: "false"
      package: github.com/reynn/downloadr/cmd
      os: linux
      preRun: GO111MODULE=on
      runGoGet: "false"
- job: package
  stage: package
  steps:
  - script:
    - echo "Packaging my application"
